1.Write a Python Program to Add Two Matrices?

In [26]:
import numpy as np
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]
B=[[2, 5, 7, 10], 
    [4, 9, 11, 1],
    [-2, 6, 9, 20]]
addition = np.add(A,B)
print(f"The first matrix is: \n {A}")
print(f"\nThe second matrix is:\n {B}")
print(f"\nThe sum of 2 matrices are: \n {addition}")

The first matrix is: 
 [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]

The second matrix is:
 [[2, 5, 7, 10], [4, 9, 11, 1], [-2, 6, 9, 20]]

The sum of 2 matrices are: 
 [[ 3  9 12 22]
 [-1 17 20  1]
 [-8 13 20 39]]


2.Write a Python Program to Multiply Two Matrices?

In [27]:
import numpy as np
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

res= np.matrix(X) @ np.matrix(Y)

print(f"The first matrix is: \n {X}")
print(f"\nThe second matrix is: \n {Y}")
print(f"\nThe product of 2 matrices are: \n {res}")

The first matrix is: 
 [[12, 7, 3], [4, 5, 6], [7, 8, 9]]

The second matrix is: 
 [[5, 8, 1, 2], [6, 7, 3, 0], [4, 5, 9, 1]]

The product of 2 matrices are: 
 [[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]


3.Write a Python Program to Transpose a Matrix?

In [31]:
import numpy as np
Z= [[1 ,2, 3],
    [4 ,5,6],
    [7 ,8,9]]
print(f"The transpose of a matrix is:\n {np.matrix(Z).T}")

The transpose of a matrix is:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


4.Write a Python Program to Sort Words in Alphabetic Order?

In [44]:
word = input("Enter the word to be sorted:")
w = word.split(" ")
for i in range(len(w)):
    w[i] = w[i].lower()
sort_word = sorted(w)  
print(f"The sorted word is: {' '.join(sort_word)}")    

Enter the word to be sorted:My name is Tommy Xavier
The sorted word is: is my name tommy xavier


5.Write a Python Program to Remove Punctuation From a String?

In [9]:
word = input("Enter the word:")
puct = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
for i in word:
    if i in puct:
        word = word.replace(i,"")
print(word)

Enter the word:Hi There!! It's me Malavika...
Hi There Its me Malavika
